name: CD
on:
  push:
    branches:
      - master
      - develop # TODO: あとでけす
  pull_request:
    branches:
      - master
      - develop # TODO: あとでけす
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
permissions: {}
jobs:
  install:
    strategy:
      matrix:
        one: ["production", "staging"]
        two: ["www", "api"]
        three: ["jp", "root"]
        four: ["com", "net", "app", "org"]
        five: ["public", "maintenance", "errors", "functions"]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Sync to S3
        run: aws s3 sync  ./src/api/jp/app/errors s3://umaxica.production.cloudfront.api.jp.app.errors --delete
      - name: Sync to S3
        run: aws s3 sync  ./src/api/jp/app/functions s3://umaxica.production.cloudfront.api.jp.app.functions --delete
      - name: Sync to S3
        run: aws s3 sync  ./src/api/jp/app/maintenance s3://umaxica.production.cloudfront.api.jp.app.maintenance --delete
      - name: Sync to S3
        run: aws s3 sync  ./src/api/jp/app/public s3://umaxica.production.cloudfront.api.jp.app.public --delete
      - name: Sync to S3
        run: aws s3 sync  ./src/api/jp/com/public s3://umaxica.production.cloudfront.api.jp.com.public --delete
      - name: Sync to S3
        run: aws s3 sync  ./src/www/jp/app/public s3://umaxica.production.cloudfront.www.jp.app.public --delete
