name: CD
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
  issues: write
jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      # - uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ secrets.AWS_REGION }}
      # - run: aws s3 sync ./_site s3://com.seahal --delete # ここで aws の s3 にプッシュ、url がリアルのと一致しないのに注意
      # - run: aws cloudfront create-invalidation --distribution-id E29JJUCSVJD128 --paths '/*' # ここでawsのcfのキャッシュ消去(en)
      # - run: aws cloudfront create-invalidation --distribution-id EAOO2PZTA3QQY --paths '/*' # ここで aws の cf のキャッシュ消去(pd)
